<?php
namespace Csanquer\DebugTools\Test\Output;

use Csanquer\DebugTools\Output\OutputInterface;
use Csanquer\DebugTools\Output\AbstractCli;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-09 at 12:15:32.
 */
class AbstractCliTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Csanquer\DebugTools\Output\OutputInterface
     */
    protected $output;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->output = $this->getMockForAbstractClass('Csanquer\DebugTools\Output\AbstractOutput');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Csanquer\DebugTools\Output\AbstractCli::format
     * @todo   Implement testFormat().
     */
    public function testFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
