<?php
namespace Csanquer\DebugTools\Test\Output;

use Csanquer\DebugTools\Output\OutputInterface;
use Csanquer\DebugTools\Output\ColorCli;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-09 at 12:20:06.
 */
class ColorCliTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Csanquer\DebugTools\Output\ColorCli
     */
    protected $output;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->output = new ColorCli();
    }
    
    /**
     * @todo   Implement testFormat().
     */
    public function testFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
