<?php
namespace Csanquer\DebugTools\Test\Output;

use Csanquer\DebugTools\Output\OutputInterface;
use Csanquer\DebugTools\Output\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-09 at 12:20:30.
 */
class HtmlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Csanquer\DebugTools\Output\Html
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Html;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Csanquer\DebugTools\Output\Html::format
     * @todo   Implement testFormat().
     */
    public function testFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
