<?php
namespace Csanquer\DebugTools\Test;

use Csanquer\DebugTools\Output\OutputInterface;
use Csanquer\DebugTools\Debug;
use Csanquer\DebugTools\dbg;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-09 at 12:12:00.
 */
class dbgTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Csanquer\DebugTools\dbg
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new dbg;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Csanquer\DebugTools\dbg::dump
     * @todo   Implement testDump().
     */
    public function testDump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\dbg::print_r
     * @todo   Implement testPrint_r().
     */
    public function testPrint_r()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\dbg::var_dump
     * @todo   Implement testVar_dump().
     */
    public function testVar_dump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\dbg::zval_dump
     * @todo   Implement testZval_dump().
     */
    public function testZval_dump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\dbg::backtrace
     * @todo   Implement testBacktrace().
     */
    public function testBacktrace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\dbg::asString
     * @todo   Implement testAsString().
     */
    public function testAsString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
