<?php
namespace Csanquer\DebugTools\Test;

use Csanquer\DebugTools\Debugger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-09 at 12:11:29.
 */
class DebuggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Csanquer\DebugTools\Debugger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::hasInstance
     * @todo   Implement testHasInstance().
     */
    public function testHasInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::resetInstance
     * @todo   Implement testResetInstance().
     */
    public function testResetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::setEnabled
     * @todo   Implement testSetEnabled().
     */
    public function testSetEnabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::isEnabled
     * @todo   Implement testIsEnabled().
     */
    public function testIsEnabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::append
     * @todo   Implement testAppend().
     */
    public function testAppend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::group
     * @todo   Implement testGroup().
     */
    public function testGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::endGroup
     * @todo   Implement testEndGroup().
     */
    public function testEndGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::dump
     * @todo   Implement testDump().
     */
    public function testDump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::print_r
     * @todo   Implement testPrint_r().
     */
    public function testPrint_r()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::var_dump
     * @todo   Implement testVar_dump().
     */
    public function testVar_dump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::zval_dump
     * @todo   Implement testZval_dump().
     */
    public function testZval_dump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::var_export
     * @todo   Implement testVar_export().
     */
    public function testVar_export()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csanquer\DebugTools\Debugger::backtrace
     * @todo   Implement testBacktrace().
     */
    public function testBacktrace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
